# This file is managed by gitlab-ctl. Manual changes will be
# erased! To change the contents below, edit /etc/gitlab/gitlab.rb
# and run `sudo gitlab-ctl reconfigure`.

---
production:
  db_key_base: 4d616b472a4b5dda226b9f90785e7739828f2f087facdde48670e18b470febc6b29b04c343475940404b3a005f63a59568d7814e8e5eb135d2ecddada24adcad
  secret_key_base: 9f9cc0485d676c0063eea6ecedf0959ead1fab0433abe58e377e86e2ea9c779d1b13e15780018b9b1f892f12fd1b6ade5f07c003c4a274361393d6a2c609a439
  otp_key_base: 52468de05579f0b9bd56a93e52154e0dc421459d409607ab55a3a23c9b795acf4f498439e39b88c9cf77e3d0de7d2f16305684dad7ca194539eee40688ef35b8
  openid_connect_signing_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIJKgIBAAKCAgEAzjy2Clg3i4ZCTFsTfSonImsMPSDcXXxAsTfkVaAFYCwHmfS6
    /vyyHxv49RVogmsG9gFhBkGqWkU2yGUAyC/y9BCuIaA34lSePfUZJERUL0g8ctDk
    pywe/NtmzSsgEwTbNlCSE1Bqtohc8cAvHFV1JIgvW6Kg5m8seAtOBc6kbwoZSPue
    zLleyTE/tKAQ/jNm+boJdOsUJFFqu47kcXVrsYcKO9ePvk8RRHTQg80AoUFrcSYq
    fnR2af2ChqCcIMN/nRIsZ/rb8Q+pU8aY2Bq/eRIqzdiLpzXsy+9W07zatTNyoHF0
    CxJzIRdIEWAX46xzYAJ34vbw8qMmlf6vkKd6mW5GnKOWfUgdCY1+HH7TvIPe95m5
    DVQxRsXndqAA7P9vlSZFoE77GPqMueMdnv9lL/ciugA16RkAwJ0VpvfTvcm4MKc6
    j2sqMuYn0l/rlQDiw/P6B7jQEuN/PvSeoOmnFrAOu9hvwhgi4K6TxgGnI5epHNQS
    AVSTFaN2LIrEjw4y+MxI5A1qcg6eLm2TmRvGfg7GY9p9nxsj6lV3gl4PozgXQh9v
    rJC/m//ozbyoif3hCNEUb5G+QMpJQNsuojLlrLLCudW0CzQ9m3UEqP/Lphh1dVVH
    2ibYtlauE14CQhy3ZZTH/ZIKlITgvzPCKctmQ+zxyv8qc1XDc9l7FsKWFwkCAwEA
    AQKCAgEAv8oxuDkFnpkCeqOP4iwbLKTEQuyWQdHVD3lcvEwN87u+bevrIkm5E7kd
    sj1wbSg+1vO9WOYkF8KaCY30RjZhB5ujc93dWns6lX+jG9j3OOlCXbvph5U+VANs
    /IuITmeLvFz9Gz0DoC/7z03cActvHsQO1nbMjr8AabqJmljrDeAkV3y31sbkYNGN
    3tmkM+F1d/ML7FDY8FVOnpFp3CFIP1XHrJLwOBirhC/l4Uv5s/x0gErv5Z1EqZh5
    k900lDt6J4XJCgF+HBVmcGQVq5JkUaEVcUxZwuwhBB3Vbx8HfM8VYCNhuRI1Qqa1
    /IKSdMXgnX5uIwFmXR5gOckZV7qIBQ4kTFHW673+zqc+Ggiq3Csuva1QpMil+9dY
    D/4+lf7W8eoEkB+L76XV3C4CZ2irVleS+nmjIBgtj65xaPs76DyYYT5BgJUCCV5h
    djEuwMl47grtM2hyJ3DZg8ItPRlUi37ZN62hU2ZhtuHlz0cuXGKU44yEDxpEJCMd
    anm6etTYU9nqi+qREujMApZ2Xod3lMXJBSW5MHYBgbJdhAjFnf4ymLU6bBhFYWSl
    sjkE3Cf7stmsgJKbjzwJYOnDbvXkcg94IvWmrNQRh+V106S66b018opFnG1N8X3f
    7BCyZnWd2hVaS57fhgBlfsNfJZZutJKW2wG4auGVHvkHrPTlhkkCggEBAPvAJc8Z
    y8SsJi7zeHp2Qo+WK/2WA7vJVhuBalSs3Xzw0LFv5bXL+XrLcircp10CrKBCALZk
    qtGY9W01CkeyG27Da7XrtKon1hS+Pr40njC2+nJwdjtqb/ZINYb/LKBg8ROZkhPv
    0G04zVxfsH9abLmLMSEzmlzPGa+7rMfn3m8E1fFZBw8ZffTszXXAqIe8ZCF+akiO
    Dqk3PNrGn/qCnZBhv/7e/ql+HO0XEo50CAKALbaidlD6Mx6g1CtpHGuEG1C7H3/u
    hpCKAMsuwCaNckeO8VzEjfklsQb3NWZoGpurfHWTo7kHZw0r/9E5gTgls3bW1PrV
    o6r2WN9GSBGMNxMCggEBANG35Jy1W+4JlG820dt/39143raZKW3izQgrbfHdbkYq
    HfJowrAeRA+FdRoSOAfsURtPXx5+5iPLqfhNDZOKGfK3Jkfq/4W/MAOuBk80qH/N
    D5QOXA/NDT5yjfQQ/J0Bz4nOAjZx8Z5TPaNRxrRe1BT6SJtFt8Qg55VDMyyIYFiI
    SHcGDPl9bhLCH9NeWSLlXPxAnJ6epWzmo3/i0UZrB2c8+iJvDa3JolCpdkx15S80
    N++HIEMTVUor6UADYjQ1Z5jpbNQQQjxcYMKpTf4rwInjnkXiZIDs3aj1lplgPgBn
    DZOfTo93X/lZvGpuV8kkgnF4bk6Dc0qG8FvsLo008PMCggEBAI9TGnNorUC//VEX
    ncyijUxv44WQpXmAq3wnVqD0dXiPJVEPcojoopUNRGcwjjv+rMbkLMGqWDHR0lAl
    NUASH1oU+bptgcKpwVC36sKg9DqpwbXrXvR+qVVeUNMVbZO0/Sr6cFbXXiMAhrID
    bFlk4qdTnlnXphcWdPo+b6Sz1kgASckItWMcUUBinKpgT9JPJ/aFoP7DmYcvAn9P
    O38EY63yaLsyu2tFeDRmwVLGrlS2ItBqd8+sUfQq/f/k7KAtatuwXMOZyZR6bO9A
    I3cPajNhJvp4kJd6pOlhTk6KEDP2Enph3oEVvM6b8R1tjqqnlB+hOUnA3VgUvg4H
    VjpfSG8CggEASHbHKpLL6gsrW+ZQSwz7WHZsViHEG/ETMXB4M+t0MBBbeqhSJTLA
    B7DwjoqfC7XPLKWXU107vkCgQWi2eTVt090PACimFBvExnC6Q2IJmudLK7hufRM4
    MUy52gyIjOPUR2SEhTWH7FIM6ULXavmdRIZa0jQb1EweWQf4Rbn1uIGWsHHJx+dc
    QmULRCjEmfcw0wSsWW6t8FwdQJIqB6/xxe1e7Mj8rAEQ8dgsRS0zfMUJUt2Y+zRR
    8ygLF5BTvYB6hG6bqQbZLCwrTvfbOCj8BWk+Bh285oNx7/C0Edkcc10oZsrUBWSV
    J/6myQvJj3nrDLQ1QTHQg37uzIRmbWpOmwKCAQEA5VL26AjxjHmgtmdWoEPTMIrA
    9Nm9NJSdZJ9+UrrdERkXfpAWQCCBks8dDohGux1a0NZ4zsEPWjNdBq8UCtLUourQ
    nbdQXtDvxgXnNfJ6b+yBk1zeQTaTOfBkZS5fxUAC5CzkyKWcCUyxIkxoOvD9aP6R
    t9MGXLdHcTEOf5BMtZXZ2wdHjUEyYJ94JMiymI3+2yGcADVs1cRiWtWosB2UC4WR
    xEGPiJTw0nL5xWuUkJ63y3FlBxk6JmhJBqMyCuUecVJscoig9Ofa1JMNuY+hKZWS
    fEfIH9RPjH9cgn2Xe4Qo+s5+IouU7wKF5ePqNdNxNoZNOVkfcykYNr5uB+XqfQ==
    -----END RSA PRIVATE KEY-----

